### ISSUE TITLE
peerDependency nemo@^0.4.0

### ISSUE THREAD

**Issue by erikmueller** [paypal/nemo-drivex#12]
Tried to use `nemo-drivex@0.4.5` but it seems like after 0.1.x a peer dependency was introduced which  prevents you from using `nemo@1.x`

Do I do something wrong?

**Comment by nikulkarni** [comment]
hi @erikmueller we combined both nemo-view and nemo-drivex in `nemo-view@^1.0.0`. We are recommending all users to upgrade to `nemo*@^1.0.0`. Upgrading to it will provide you all brand new features  plus it should be pretty straightforward. Let us know if you stumble upon any issues.

**Comment by grawk** [comment]
For a little more detail: the "drivex" methods are now in a generic library called "selenium-drivex":
https://github.com/grawk/selenium-drivex

These methods can now be used in any selenium project, not just nemo.

We are using selenium-drivex as a dependency in nemo-view: https://github.com/paypal/nemo-view/blob/master/lib/locreator.js#L2

The previous nemo-drivex methods can now be accessed via "nemo-view" as these generic methods:
https://github.com/paypal/nemo-view/blob/master/README.md#genericunderbar-methods

The method signatures of the generic methods are different than the previous nemo-drivex methods. The nemo-drivex methods expect a JSON argument `{'locator': '#xyz', 'type': 'css'}` whereas the nemo-view generic methods expect a string argument `'#xyz'`.

If it is **required** to mix nemo-drivex into nemo@1.x then it would be fairly simple to release a 1.0 compatible version of nemo-drivex. But I think it is probably best to migrate to nemo-view.

**Comment by erikmueller** [comment]
@grawk thank you very much for this detailed elaboration 😊 will just do as you suggested. Changes look nice, thanks for the work.
