### ISSUE TITLE
Installation fails with errors and warnings

### ISSUE THREAD

**Issue by benmarten** [paypal/nemo-drivex#13]
Just wanted to add nemo-drivex plugin to one of my projects:

Ben@Bens-MacBook-Pro ~/N/jemo> npm install nemo-drivex --save
npm WARN package.json jemo@0.0.1 No repository field.
npm WARN peerDependencies The peer dependency nemo@^0.4.0 included from nemo-drivex will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency nemo-locatex@^0.4.0 included from nemo-drivex will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency nemo@^0.4.0 included from nemo-locatex will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/Ben/.nvm/v0.12.2/bin/node" "/Users/Ben/.nvm/v0.12.2/bin/npm" "install" "nemo-drivex" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package nemo does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer nemo-locatex@0.4.2 wants nemo@^0.4.0
npm ERR! peerinvalid Peer nemo-drivex@0.4.5 wants nemo@^0.4.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ben/NodeProjects/jemo/npm-debug.log

**Comment by nikulkarni** [comment]
Hey @benmarten we had a similar issue open a few days back- https://github.com/paypal/nemo-drivex/issues/12 Can you check and let us know if that answers your question?

**Comment by benmarten** [comment]
Ah ok, that's fine. I didn't know that it's deprecated. Maybe add a note to the top of the readme?
I solved the npm issue by deleting the nemo_modules/xyz_package folder...

**Comment by nikulkarni** [comment]
Good idea. What say @grawk ?
